# ════════════════════════════════════════════════════════════════
# 🔥 ЧЁРНЫЙ СПИСОК ПО ДОМЕНАМ
# ════════════════════════════════════════════════════════════════
BLACKLIST = {
        'godsbay.ru': [
        # Страницы-алфавитные указатели (мусор)
        '/all.html',
        '/all_b.html',
        '/all_v.html',
        '/all_g.html',
        '/all_d.html',
        '/all_e.html',
        '/all_j.html',
        '/all_z.html',
        '/all_i.html',
        '/all_l.html',
        '/all_m.html',
        '/all_n.html',
        '/all_o.html',
        '/all_p.html',
        '/all_r.html',
        '/all_s.html',
        '/all_t.html',
        '/all_f.html',
        '/all_h.html',
        '/all_zt.html',
        '/all_ch.html',
        '/all_sh.html',
        '/all_ye.html',
        '/all_yu.html',
        '/all_ya.html',
        '/all1.html',
        '/all2.html',
        
        # Служебные
        '/about.html',
        '/index.html',
        '/civilizations/index.html',
        
        # Если есть другие разделы-оглавления
        '/antique/',
        '/egypt/',
        '/celts/',
        '/vikings/',
        '/maya/',
        '/slavs/',
        '/orient/',
        '/civilizations/',
        '/paint/',
    ],
    'cyberleninka.ru': [
        # Технические страницы
        '/terms.html',
        '/policy.html',
        '/app.css',
        '/fonts/',
        '/images/',
        '/js/',
        '/css/',
        '/assets/'
    ],
    'azbyka.ru': [
        # Главные разделы
        '/otechnik/settings/',
        '/otechnik/assets/',
        '/otechnik/profile/',
        '/otechnik/search/',
        '/otechnik/login/',
        '/otechnik/register/',
        '/otechnik/feedback/',
        '/otechnik/about/',
        '/otechnik/books/',
        
        # Другие разделы сайта
        '/forum/',
        '/biblia/',
        '/dictionary',
        '/pravo/',
        '/fiction/',
        '/gid',
        '/cerkov',
        '/drevo-sajta',
        '/1/',
        '/wp-content/',
        '/wp-includes/',
        '/news/',
        '/foto/',
        '/audio/',
        '/video/',
        '/days/',
        '/quiz/',
        '/crosswords/',
        '/test/',
        '/viktorina/',
        '/games/',
        '/memo/',
        '/death/',
        '/art/',
        '/apokalipsis/',
        '/vopros/',
        '/life/',
        '/ikona/',
        '/katehizacija/',
        '/way/',
        '/opros/',
        '/shemy/',
        '/propovedi/',
        '/sueverie/',
        '/quotes',
        '/chinaorthodox/',
        '/japanorthodox/',
        '/znakomstva/',
        '/deti/',
        '/trezvost/',
        '/zdorovie/',
        '/recept/',
        '/garden/',
        '/semya/',
        '/telegram-kanaly',
        '/extension',
        '/kliros/',
        '/palomnik/',
        '/worships/',
        '/chaso-slov/',
        '/molitvoslov/',
        '/bogosluzhenie/',
        '/psalms/',
        
        # Служебные страницы (только для azbyka.ru)
        '/obratnaja-svjaz',
        '/obratnaja-svjaz/',
        '/about-all',
        '/svjazat-s-administraciej',
        '/social-media',
        '/job',
        '/azbuka-very-na-vashem-sajte',
        '/allprojects',
        '/kak-pomoch/',
        '/bozhestvennaja-liturgija/',
        '/bogosluzhenie-online/',
        '/lyubov/',
        '/auth/',
        
        # Книги других авторов (если не нужны)
        '/otechnik/Georgij_Zadonskij/pisma/',
    ],
    
    # Можно добавить другие сайты:
    # 'example.com': [
    #     '/admin/',
    #     '/cdn/',
    # ],
}
# ════════════════════════════════════════════════════════════════