# ════════════════════════════════════════════════════════════════
# 🔥 ЧЁРНЫЙ СПИСОК ПО ДОМЕНАМ
# ════════════════════════════════════════════════════════════════
BLACKLIST = {
    'azbyka.ru': [
        # Главные разделы (мусор)
        '/otechnik/settings/',
        '/otechnik/assets/',
        '/otechnik/profile/',
        '/otechnik/search/',
        '/otechnik/login/',
        '/otechnik/register/',
        '/otechnik/feedback/',
        '/otechnik/about/',
        '/otechnik/books/',
        
        # Другие разделы сайта
        '/forum/',
        '/biblia/',
        '/dictionary',
        '/pravo/',
        '/fiction/',
        '/gid',
        '/cerkov',
        '/drevo-sajta',
        '/1/',
        '/wp-content/',
        '/wp-includes/',
        '/news/',
        '/foto/',
        '/audio/',
        '/video/',
        '/days/',
        '/quiz/',
        '/crosswords/',
        '/test/',
        '/viktorina/',
        '/games/',
        '/memo/',
        '/death/',
        '/art/',
        '/apokalipsis/',
        '/vopros/',
        '/life/',
        '/ikona/',
        '/katehizacija/',
        '/way/',
        '/opros/',
        '/shemy/',
        '/propovedi/',
        '/sueverie/',
        '/quotes',
        '/chinaorthodox/',
        '/japanorthodox/',
        '/znakomstva/',
        '/deti/',
        '/trezvost/',
        '/zdorovie/',
        '/recept/',
        '/garden/',
        '/semya/',
        '/telegram-kanaly',
        '/extension',
        '/kliros/',
        '/palomnik/',
        '/worships/',
        '/chaso-slov/',
        '/molitvoslov/',
        '/bogosluzhenie/',
        '/psalms/',
        
        # Служебные страницы (только для azbyka.ru)
        '/obratnaja-svjaz',
        '/obratnaja-svjaz/',
        '/about-all',
        '/svjazat-s-administraciej',
        '/social-media',
        '/job',
        '/azbuka-very-na-vashem-sajte',
        '/allprojects',
        '/kak-pomoch/',
        '/bozhestvennaja-liturgija/',
        '/bogosluzhenie-online/',
        '/lyubov/',
        '/auth/',
        
        # Книги других авторов (если не нужны)
        '/otechnik/Georgij_Zadonskij/pisma/',
    ],
    
    # Можно добавить другие сайты:
    # 'example.com': [
    #     '/admin/',
    #     '/cdn/',
    # ],
}
# ════════════════════════════════════════════════════════════════